// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/10       [336394]
Creator        : gartoni
Date           : Thu Mar 13 16:35:25 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/g/gartoni/Training
Training events: 76077
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Normalize" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "True" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "5.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "6.000000e-01" [Learning rate for GradBoost algorithm]
nEventsMin: "200" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
PruneMethod: "costcomplexity" [Method used for pruning (removal) of statistically insignificant branches]
NNodesMax: "8" [Max number of nodes in tree]
MaxDepth: "4" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "76077" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
dijet_invmass                 dijet_invmass                 dijet_invmass                 m_{jj} [MeV]                                                    'F'    [130000.882812,4502359.5]
dijet_deltaeta                dijet_deltaeta                dijet_deltaeta                #Delta#eta                                                      'F'    [0.000602945685387,8.58735179901]
leading_jet_pt                leading_jet_pt                leading_jet_pt                lead jet p_{T} [MeV]                                            'F'    [25732.546875,678091.8125]
subleading_jet_pt             subleading_jet_pt             subleading_jet_pt             sub jet p_{T} [MeV]                                             'F'    [25000.3222656,436327.03125]
leading_jet_eta               leading_jet_eta               leading_jet_eta               lead jet #eta                                                   'F'    [-4.52842617035,4.51303291321]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dijet_invmass", "dijet_deltaeta", "leading_jet_pt", "subleading_jet_pt", "leading_jet_eta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803909,0.314327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524514,0.0249825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331146,-0.168882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234414,-0.265994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144631,-0.311379) , 
1, -0.349695, 1, 0, 0.225216,-0.274784) , 
0, -0.98834, 0, 0, 0.294725,-0.205275) , 
0, -0.959186, 0, 0, 0.398087,-0.101913) , 
0, -0.904762, 0, 0, 0.619161,0.119161)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870207,0.24899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638586,0.0477831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394993,-0.0578929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286313,-0.116361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220272,-0.165912) , 
3, -0.931669, 0, 0, 0.25166,-0.138185) , 
0, -0.977286, 0, 0, 0.321143,-0.0985449) , 
0, -0.946982, 0, 0, 0.492535,-0.0216252) , 
0, -0.814435, 0, 0, 0.617715,0.0578068)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.871529,0.16401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681871,0.0454083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362379,-0.0432621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290245,-0.249562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234302,-0.157136) , 
0, -0.961992, 0, 0, 0.262128,-0.167014) , 
2, -0.592434, 1, 0, 0.354649,-0.0507032) , 
0, -0.927443, 0, 0, 0.497472,-0.0111605) , 
0, -0.809524, 0, 0, 0.617057,0.0295922)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660547,0.0565905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539869,-0.0319309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533404,-0.041942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402388,-0.125868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176364,-0.214028) , 
2, -0.982409, 0, 0, 0.387267,-0.12744) , 
3, -0.933677, 0, 0, 0.403923,-0.117112) , 
2, -0.938418, 0, 0, 0.469835,-0.0737176) , 
2, -0.907621, 0, 0, 0.619081,0.0176432)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673066,0.0306457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463185,-0.281246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318761,-0.0364148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317919,-0.0936414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216037,-0.182771) , 
1, -0.843333, 0, 0, 0.287951,-0.0953673) , 
2, -0.74189, 1, 0, 0.302569,-0.0655938) , 
0, -0.922064, 0, 0, 0.317189,-0.0786863) , 
1, -0.530406, 0, 0, 0.61946,0.00820588)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903797,0.133213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585093,0.0026715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498496,-0.0288988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461356,-0.123384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240892,-0.0472823) , 
0, -0.959318, 0, 0, 0.364334,-0.0882765) , 
3, -0.954279, 0, 0, 0.423081,-0.0611443) , 
2, -0.91479, 0, 0, 0.550799,-0.0112803) , 
0, -0.714285, 0, 0, 0.619283,0.00490214)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686481,0.0311944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625277,0.0166305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566694,-0.0299682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45,-0.0606396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241976,-0.114985) , 
2, -0.977321, 0, 0, 0.434247,-0.0592415) , 
3, -0.948429, 0, 0, 0.480244,-0.0471293) , 
2, -0.841239, 0, 0, 0.531667,-0.0262218) , 
3, -0.916699, 0, 0, 0.618895,0.000705455)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692704,0.0171797) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398441,-0.0221993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270302,-0.0802993) , 
1, -0.704805, 0, 0, 0.360735,-0.0320571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357826,-0.181907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319899,-0.360975) , 
2, -0.150764, 1, 0, 0.339435,-0.186027) , 
2, -0.279968, 1, 0, 0.359834,-0.0385669) , 
1, -0.436608, 0, 0, 0.618651,0.000943093)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.914579,0.0951587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818194,0.0195323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457295,-0.0165495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349437,-0.261189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247623,-0.0343884) , 
0, -0.926275, 0, 0, 0.29332,-0.102551) , 
2, -0.412125, 1, 0, 0.452882,-0.01683) , 
0, -0.85862, 0, 0, 0.575067,-0.0074107) , 
0, -0.62887, 0, 0, 0.618068,-0.00132827)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660934,0.0110809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621489,-0.0668951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374684,0.00484286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2312,-0.0149707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.120831,-0.0875316) , 
2, -0.959214, 0, 0, 0.197628,-0.0278082) , 
0, -0.987537, 0, 0, 0.328694,-0.00378005) , 
1, -0.0564322, 0, 0, 0.46696,-0.0278648) , 
2, -0.904762, 0, 0, 0.616749,-0.00058278)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697055,0.0099733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351951,-0.019252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434188,0.0188009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.338085,-0.0868001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308475,-0.151731) , 
2, -0.421914, 0, 0, 0.329142,-0.0731465) , 
4, -0.244242, 1, 0, 0.34645,-0.058794) , 
2, -0.493064, 1, 0, 0.351255,-0.0214508) , 
1, -0.428571, 0, 0, 0.617933,0.000382371)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692173,0.0198389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.953551,0.173348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567965,-0.0124921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297551,-0.0114821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203263,-0.0792798) , 
0, -0.983585, 0, 0, 0.232858,-0.0432301) , 
1, -0.498887, 0, 0, 0.533976,-0.0133992) , 
0, -0.395308, 0, 0, 0.542694,-0.0116888) , 
3, -0.904762, 0, 0, 0.618986,0.000749625)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757273,0.0144066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7308,-0.282618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443691,-0.00637962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242285,-0.0220211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218179,-0.0883976) , 
1, -0.867633, 1, 0, 0.23129,-0.0367302) , 
1, -0.785918, 0, 0, 0.421888,-0.00856093) , 
0, -0.767153, 0, 0, 0.426701,-0.0103136) , 
1, -0.250614, 0, 0, 0.619689,0.000971448)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684554,0.0112552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769294,-0.0628055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474373,-0.00140284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343499,-0.0404881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283859,-0.102672) , 
3, -0.99834, 0, 0, 0.334008,-0.043732) , 
3, -0.988425, 0, 0, 0.458491,-0.00599578) , 
1, 0.142944, 0, 0, 0.527115,-0.0127437) , 
3, -0.919016, 0, 0, 0.617512,-0.00126864)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.918249,0.0510646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759614,-0.0425852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93149,0.108427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558745,0.000999153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517644,-0.0381191) , 
2, -0.522593, 1, 0, 0.555911,-0.00092579) , 
0, -0.673563, 0, 0, 0.566027,0.000111658) , 
1, 0.221762, 0, 0, 0.577551,-0.00150635) , 
0, -0.619047, 0, 0, 0.618061,0.000765277)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93458,0.0739268) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685729,0.0171264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559419,-0.00777743) , 
3, -0.843807, 0, 0, 0.595029,-0.00127683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656457,-0.220841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278323,-0.0192404) , 
1, -0.565767, 0, 0, 0.488586,-0.0677775) , 
2, -0.238095, 1, 0, 0.59362,-0.00215721) , 
0, -0.523809, 0, 0, 0.619004,-0.000280416)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674391,0.00975898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650342,0.000431211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532523,-0.0400183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624386,-0.0201521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310266,0.0138281) , 
0, -0.898673, 0, 0, 0.414299,0.0021634) , 
2, -0.909319, 0, 0, 0.461636,-0.0118474) , 
3, -0.942416, 0, 0, 0.572636,-0.00469524) , 
2, -0.809524, 0, 0, 0.619512,0.000127319)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641527,0.000451874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342988,0.016096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253917,0.00639345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218296,-0.0536095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145392,-0.148651) , 
4, -0.0540831, 1, 0, 0.190424,-0.0608023) , 
4, 0.179439, 0, 0, 0.208414,-0.0423568) , 
3, -0.749942, 0, 0, 0.250863,-0.0251959) , 
1, -0.714286, 0, 0, 0.616164,-0.00134121)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660709,-0.103233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657588,0.00672323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336808,0.000126249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222581,0.0292191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208512,-0.0802659) , 
2, -0.639577, 0, 0, 0.213584,-0.0326827) , 
3, -0.818703, 0, 0, 0.267782,-0.0182647) , 
1, -0.619048, 0, 0, 0.61929,0.00242295) , 
3, -0.52381, 0, 0, 0.620115,0.00125419)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804896,-0.00624398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414888,-0.0111405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407446,0.0184708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369124,0.0447726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360117,-0.0234239) , 
3, -0.909763, 1, 0, 0.363332,-0.000403821) , 
2, -0.74732, 1, 0, 0.395533,0.0118369) , 
1, -0.143571, 0, 0, 0.397371,0.00961588) , 
0, -0.907217, 0, 0, 0.621062,0.00244871)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684422,0.0106333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65459,0.00376285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624332,-0.0269215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423429,0.00367697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25646,-0.0275103) , 
1, -0.636516, 0, 0, 0.358701,-0.00541663) , 
1, -0.412829, 0, 0, 0.508844,-0.0137901) , 
4, -0.17299, 1, 0, 0.590626,-0.0046282) , 
4, 0.334269, 0, 0, 0.617983,-0.00125395)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910997,0.0366246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589749,0.0823632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570342,-0.00342504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380543,0.0806699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243997,0.0166648) , 
3, -0.663309, 0, 0, 0.266347,0.0183237) , 
1, -0.72064, 0, 0, 0.546605,-0.00108891) , 
4, -0.806244, 1, 0, 0.547003,-0.00040962) , 
0, -0.721653, 0, 0, 0.619985,0.00222175)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972398,0.160658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841754,-0.119272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688832,-0.00222512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369971,0.016517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350044,-0.0117237) , 
4, -0.193304, 0, 0, 0.364622,0.006967) , 
1, -0.426013, 0, 0, 0.611453,0.000515967) , 
1, 0.506718, 0, 0, 0.615206,-0.000252788) , 
0, -0.238095, 0, 0, 0.620881,0.000352049)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709911,-0.0278669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671615,-0.0134268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854645,0.0294516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676525,-0.0400893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398162,0.00488063) , 
0, -0.903935, 0, 0, 0.45209,-0.00264109) , 
0, -0.855878, 0, 0, 0.588497,0.00313062) , 
4, 0.428571, 0, 0, 0.607808,0.000340139) , 
3, -0.714286, 0, 0, 0.617525,-0.0011298)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721926,0.00105988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600866,0.0806766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407677,0.0167095) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440587,-0.0267022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294569,-0.00608129) , 
1, -0.562871, 0, 0, 0.378511,-0.0150772) , 
4, -0.465321, 1, 0, 0.380811,-0.0127673) , 
3, -0.428571, 0, 0, 0.385328,-0.0112034) , 
1, -0.344287, 0, 0, 0.616569,-0.00304019)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862368,-0.0465003) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613399,-0.0283736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600763,0.00600476) , 
2, -0.45062, 0, 0, 0.601409,0.00338967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339001,0.168725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240708,-0.0103687) , 
1, -0.970206, 1, 0, 0.285361,0.0425121) , 
1, -0.937409, 0, 0, 0.597842,0.00383123) , 
1, 0.314428, 0, 0, 0.620098,0.00195371)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659899,0.0915184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624883,-0.000426631) , 
2, -0.116475, 0, 0, 0.625123,4.10146e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323344,-0.000389174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174731,-0.0503951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152387,-0.133882) , 
2, -0.634505, 0, 0, 0.163676,-0.0589751) , 
3, -0.773677, 0, 0, 0.226901,-0.0357409) , 
1, -0.904674, 0, 0, 0.618254,-0.000576215)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691074,-0.0196566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708526,0.0265928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608597,0.00289152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212788,-0.0303232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186115,-0.0994478) , 
4, -0.0353006, 0, 0, 0.201213,-0.036734) , 
1, -0.910717, 0, 0, 0.601146,0.00134029) , 
4, -0.462785, 1, 0, 0.613622,0.00314177) , 
4, -0.6168, 1, 0, 0.62069,0.0016742)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653431,0.0537469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621346,-0.00609657) , 
2, -0.260282, 0, 0, 0.621868,-0.00372191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335095,0.165961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258698,-0.0363066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194602,0.0771578) , 
3, -0.805478, 0, 0, 0.225561,0.00608869) , 
2, -0.674229, 1, 0, 0.266497,0.0426535) , 
1, -0.906133, 0, 0, 0.615892,-0.00294204)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62578,-0.0546553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8729,-0.0128994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760764,0.0389482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658359,-0.0323907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400086,0.0060632) , 
0, -0.90282, 0, 0, 0.446764,-0.000415982) , 
0, -0.863946, 0, 0, 0.497835,0.0042715) , 
0, -0.809524, 0, 0, 0.617357,0.00127842) , 
4, 0.809791, 0, 0, 0.617479,0.000682602)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76107,0.00991472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567222,0.00645707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303901,0.0182051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270168,-0.029506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237491,0.0283137) , 
2, -0.658073, 1, 0, 0.266194,-0.0195411) , 
4, -0.233434, 1, 0, 0.276408,-0.0102727) , 
0, -0.968501, 0, 0, 0.43602,-0.00169511) , 
1, -0.238095, 0, 0, 0.621499,0.0027309)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642725,0.00825491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648505,-0.000974674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695712,0.0318161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.799191,-0.0679944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450251,-0.0136415) , 
0, -0.808149, 0, 0, 0.520087,-0.0170676) , 
3, -0.851679, 0, 0, 0.545443,-0.0115332) , 
2, -0.821624, 0, 0, 0.597983,-0.00595839) , 
4, 0.142857, 0, 0, 0.61665,-0.00112611)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807327,-0.194009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.937635,0.0612009) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610959,-0.000113937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410271,-0.0165845) , 
3, -0.971152, 0, 0, 0.583739,-0.00203104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568509,-0.0984855) , 
3, -0.393956, 1, 0, 0.583633,-0.00248652) , 
0, -0.572823, 0, 0, 0.614819,-0.000758873) , 
1, 0.619065, 0, 0, 0.61647,-0.00142699)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.867457,0.0291622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580049,0.00169773) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71687,0.0640814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662421,-0.0991128) , 
1, 0.0891938, 1, 0, 0.694054,0.0011678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237536,-0.104574) , 
0, -0.932463, 0, 0, 0.546437,-0.0313671) , 
4, 0.701779, 1, 0, 0.579085,0.000313471) , 
1, 0.215732, 0, 0, 0.618984,0.00207783)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807514,-0.00675131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59843,0.0414835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370101,0.00838796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311166,-0.0351642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253499,0.0624151) , 
2, -0.458055, 1, 0, 0.302775,-0.0168997) , 
2, -0.729949, 1, 0, 0.355639,0.00221834) , 
0, -0.931977, 0, 0, 0.403016,0.00920291) , 
0, -0.904761, 0, 0, 0.622432,0.00222437)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706468,0.0535932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.951932,0.0702862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63977,-0.00478948) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39901,0.0690489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239154,-0.0394098) , 
3, -0.593455, 0, 0, 0.249078,-0.0223276) , 
1, -0.6539, 0, 0, 0.606098,-0.0050131) , 
0, -0.333333, 0, 0, 0.614786,-0.0044805) , 
3, -0.428571, 0, 0, 0.615773,-0.00406409)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619294,0.00318074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936849,0.00110968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699553,-0.0974252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464944,0.0675341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223608,-0.0798564) , 
1, -0.657599, 0, 0, 0.295691,-0.0183802) , 
1, -0.51981, 0, 0, 0.506581,-0.0382035) , 
0, -0.57273, 0, 0, 0.594031,-0.030389) , 
2, -0.427784, 1, 0, 0.618195,0.000800259)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644138,0.000932049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366316,0.122051) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358671,0.124334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252278,0.0239197) , 
1, -0.777418, 0, 0, 0.265598,0.0235661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226129,-0.0677471) , 
1, -0.753735, 1, 0, 0.260472,0.0143991) , 
1, -0.727814, 0, 0, 0.268328,0.0196119) , 
1, -0.714207, 0, 0, 0.619936,0.00186761)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720585,-0.00437888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55219,0.0521248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512849,-0.0221042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413644,0.000554483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271653,0.01796) , 
1, -0.643759, 0, 0, 0.369621,0.00407421) , 
3, -0.619047, 0, 0, 0.380784,0.00241616) , 
1, -0.376574, 0, 0, 0.397922,0.00654727) , 
1, -0.345394, 0, 0, 0.619745,0.000116788)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685898,-0.020301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725483,0.0858806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697685,0.0289441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683885,-0.0240353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586918,-0.00083729) , 
4, -0.603443, 1, 0, 0.598194,-0.00238413) , 
4, 0.455528, 0, 0, 0.604016,-0.00117276) , 
4, -0.85261, 1, 0, 0.604948,-0.000649518) , 
4, 0.520972, 0, 0, 0.617294,-0.00251281)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659588,0.00365586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302743,0.0144437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288548,0.0484762) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363547,-0.0046605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213397,-0.0591596) , 
3, -0.760588, 0, 0, 0.255848,-0.0300829) , 
2, -0.371488, 0, 0, 0.259136,-0.0241995) , 
4, -0.116074, 1, 0, 0.274537,-0.0119499) , 
1, -0.618973, 0, 0, 0.620639,0.00105989)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687777,0.068171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67311,-0.00208995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331028,0.0239188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363197,-0.0113136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256915,-0.0601493) , 
1, -0.614033, 0, 0, 0.30016,-0.0310579) , 
4, -0.387019, 0, 0, 0.327912,0.0127879) , 
1, -0.52381, 0, 0, 0.618857,0.00080325) , 
4, 0.809385, 0, 0, 0.619871,0.0015175)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682131,0.00429678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659886,-0.00206654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537907,-0.0391691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643484,0.0275985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493166,-0.0141014) , 
3, -0.72143, 0, 0, 0.504249,-0.00906999) , 
2, -0.628821, 0, 0, 0.511516,-0.0124227) , 
4, 0.2392, 0, 0, 0.586475,-0.00683615) , 
4, -0.331462, 1, 0, 0.614144,-0.00403952)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680763,-0.00635943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592602,0.0826058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575711,-0.0128506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56505,0.0354458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452099,-0.0022117) , 
3, -0.963372, 0, 0, 0.485907,0.00724401) , 
3, -0.951919, 0, 0, 0.520612,0.000615587) , 
2, -0.624947, 0, 0, 0.52622,0.00435434) , 
3, -0.922335, 0, 0, 0.61799,-0.000567676)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708095,0.0210844) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870551,-0.0114731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733319,0.0248164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620132,-0.0487076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393209,-0.000292187) , 
0, -0.906718, 0, 0, 0.413495,-0.00381493) , 
0, -0.891171, 0, 0, 0.497524,0.00211742) , 
0, -0.809523, 0, 0, 0.613649,2.41279e-05) , 
4, -0.714304, 1, 0, 0.617301,0.000577514)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660655,0.00018407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475821,-0.0085504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570116,0.0609163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430019,0.0155383) , 
2, -0.92659, 0, 0, 0.471404,0.0251161) , 
4, -0.141253, 1, 0, 0.473436,0.0099636) , 
2, -0.909297, 0, 0, 0.620507,0.00222961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55106,-0.124462) , 
2, -0.047619, 1, 0, 0.620094,0.00183363)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677144,0.0113993) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603296,-0.000705888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550341,-0.0181441) , 
4, -0.140786, 1, 0, 0.57369,-0.00839684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42881,0.114586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230137,-0.0234623) , 
0, -0.99241, 0, 0, 0.31799,0.0361997) , 
1, -0.6185, 0, 0, 0.566724,-0.00718185) , 
2, -0.809524, 0, 0, 0.617549,-0.000818222)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664444,-0.00139565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477578,-0.0135076) , 
3, -0.950169, 0, 0, 0.616125,-0.0035738) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673517,0.15421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603362,0.0525586) , 
4, 0.0216491, 1, 0, 0.640844,0.0578711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571087,-0.027622) , 
3, -0.714052, 1, 0, 0.615674,0.0311185) , 
2, -0.260282, 1, 0, 0.616117,-0.00297918)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658695,0.000427024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541985,0.0274249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626941,-0.0582163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391213,0.00153518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234741,0.0498766) , 
0, -0.974389, 0, 0, 0.33826,0.0132864) , 
0, -0.820407, 0, 0, 0.386464,0.00237739) , 
2, -0.95054, 0, 0, 0.488858,0.0164373) , 
2, -0.906571, 0, 0, 0.621274,0.0038351)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697663,0.0193662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641954,0.0771445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703723,0.0636556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649282,-0.000307485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273004,-0.0153802) , 
1, -0.624449, 0, 0, 0.609724,-0.00133833) , 
3, -0.393956, 0, 0, 0.610472,-0.00099104) , 
2, -0.0469779, 0, 0, 0.610668,-0.000714409) , 
4, 0.619738, 0, 0, 0.618387,0.000504574)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669382,-0.0125344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601692,0.000857439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747339,0.0424488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470088,-0.00862583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322839,0.0467488) , 
1, -0.589033, 0, 0, 0.422696,0.00568546) , 
1, -0.281234, 0, 0, 0.579912,0.0166779) , 
4, 0.142767, 1, 0, 0.597767,0.00350533) , 
4, 0.333248, 0, 0, 0.618729,8.32019e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625248,-0.0208553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677331,0.0092476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592496,-0.0183603) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52906,-0.0348172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446056,0.00188209) , 
4, -0.71148, 1, 0, 0.453861,-0.00146106) , 
2, -0.918307, 0, 0, 0.523943,-0.0079821) , 
2, -0.868033, 0, 0, 0.617476,0.000397208) , 
2, -0.538103, 0, 0, 0.618146,-0.000624101)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704378,0.0168988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895925,0.0142328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804906,-0.044201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497077,-0.0153369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495905,0.00273743) , 
2, -0.772812, 0, 0, 0.496298,-0.00211831) , 
0, -0.808201, 0, 0, 0.529221,-0.00435848) , 
0, -0.748262, 0, 0, 0.604506,-0.00241626) , 
4, 0.52381, 0, 0, 0.619415,-0.0004302)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671225,-0.0045798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8277,-0.0183962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636022,0.0371185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666704,-0.0108449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374385,0.0111605) , 
0, -0.929438, 0, 0, 0.468166,0.00399334) , 
1, 0.0289854, 0, 0, 0.488402,0.00762785) , 
0, -0.814434, 0, 0, 0.577724,0.00314793) , 
2, -0.808258, 0, 0, 0.620419,0.000506317)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70918,0.0237253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647938,0.00336387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469607,-0.0101751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274316,-0.0816354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239797,-0.0174947) , 
2, -0.962308, 0, 0, 0.259138,-0.0496723) , 
3, -0.986458, 0, 0, 0.445098,-0.0139228) , 
2, -0.911647, 0, 0, 0.610799,-0.000760284) , 
4, -0.619048, 1, 0, 0.619259,0.00067696)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786722,0.00480808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472368,-0.00176065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519182,0.00352777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5179,-0.067861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267739,-0.0166671) , 
0, -0.976062, 0, 0, 0.442576,-0.0460753) , 
4, -0.541323, 0, 0, 0.453158,-0.0393143) , 
4, -0.519016, 0, 0, 0.470912,-0.0042851) , 
1, -0.142741, 0, 0, 0.615992,-0.00105447)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667782,-0.00353329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567347,0.100792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330924,0.000537498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270354,-0.0127297) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258869,0.10058) , 
1, -0.625327, 0, 0, 0.263797,0.02873) , 
3, -0.908531, 0, 0, 0.313403,0.0078082) , 
0, -0.89461, 0, 0, 0.323785,0.010948) , 
1, -0.537255, 0, 0, 0.616989,-0.000458799)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681088,-0.011507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631799,0.00707101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264862,-0.00951224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25306,-0.0273368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148651,-0.124142) , 
0, -0.985854, 0, 0, 0.205468,-0.0421868) , 
1, -0.91807, 0, 0, 0.25194,-0.0141749) , 
1, -0.71402, 0, 0, 0.603217,0.00361053) , 
4, 0.425188, 0, 0, 0.620789,0.00112287)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639423,-0.00629256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625177,0.00132861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505572,0.0247343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46949,0.0110864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464785,-0.0701253) , 
2, -0.396261, 0, 0, 0.466871,-0.0223831) , 
2, -0.551707, 1, 0, 0.499756,0.0136925) , 
4, -0.0186302, 1, 0, 0.605155,0.00296118) , 
4, 0.144337, 0, 0, 0.619538,-6.3964e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688976,0.0224853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870051,0.0353583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703783,-0.00403656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393179,0.000848243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251435,-0.0269712) , 
0, -0.974312, 0, 0, 0.307982,-0.012264) , 
0, -0.950959, 0, 0, 0.560078,-0.00625961) , 
1, 0.22054, 0, 0, 0.589797,-0.00417935) , 
4, 0.333248, 0, 0, 0.618994,0.00141234)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631158,-0.0041674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374122,0.0793842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237872,0.0792557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230971,-0.0472781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206658,0.05628) , 
2, -0.581653, 1, 0, 0.222804,-0.0124641) , 
0, -0.990083, 1, 0, 0.228962,0.0108283) , 
0, -0.958276, 0, 0, 0.258429,0.0201212) , 
1, -0.809193, 0, 0, 0.617236,-0.00204131)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.961432,0.0847408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642468,-0.036307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767803,0.0715452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642377,-0.00547677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4627,0.00413239) , 
2, -0.914957, 0, 0, 0.606417,-0.00214988) , 
3, -0.56925, 0, 0, 0.607824,-0.00177143) , 
3, -0.523803, 0, 0, 0.608472,-0.00218078) , 
0, -0.333333, 0, 0, 0.617943,-0.00165968)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660195,0.00574636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552652,-0.0599683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475808,0.00274061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365244,-0.0501692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290684,0.0044281) , 
3, -0.975937, 0, 0, 0.334599,-0.0269593) , 
2, -0.961711, 0, 0, 0.436691,-0.00566344) , 
3, -0.919522, 0, 0, 0.456439,-0.0130565) , 
2, -0.91211, 0, 0, 0.618931,0.000297473)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65529,-0.0500413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643009,-0.00355974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619848,0.00416567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513495,-0.00377013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498642,0.0506392) , 
2, -0.793163, 0, 0, 0.506488,0.0193464) , 
4, 0.00420036, 1, 0, 0.603887,0.0052042) , 
4, 0.139473, 0, 0, 0.620573,0.00196523) , 
4, -0.806999, 1, 0, 0.621019,0.00148641)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684975,0.00716319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591086,-0.00404385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858697,0.079275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5423,-0.021429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5196,-0.122057) , 
2, -0.45895, 1, 0, 0.540487,-0.0206594) , 
1, 0.105764, 0, 0, 0.564362,-0.0160249) , 
4, -0.20416, 0, 0, 0.587813,-0.0044849) , 
4, -0.330913, 1, 0, 0.616043,-0.00182787)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656508,-0.0416694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790603,-0.00342642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597747,0.0301197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492421,-0.0250913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338763,0.0115822) , 
0, -0.945045, 0, 0, 0.359988,0.00504633) , 
0, -0.932079, 0, 0, 0.391348,0.00799054) , 
0, -0.916087, 0, 0, 0.618047,0.00233539) , 
4, 0.714815, 0, 0, 0.619555,0.00116636)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708733,0.0503239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65638,0.000727713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478878,-0.00595064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233606,-0.0144117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227122,-0.103634) , 
3, -0.982956, 1, 0, 0.230356,-0.0541523) , 
2, -0.976236, 0, 0, 0.463659,-0.00833916) , 
2, -0.903712, 0, 0, 0.614207,-0.00145983) , 
4, 0.714555, 0, 0, 0.617926,-7.90146e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656647,0.00404449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289346,-0.0328901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30621,0.0442077) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250559,0.00271579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186993,-0.0990023) , 
4, 0.0923447, 1, 0, 0.239266,-0.00909431) , 
4, 0.223598, 0, 0, 0.255765,0.000477653) , 
1, -0.768174, 0, 0, 0.272776,-0.0124832) , 
1, -0.625689, 0, 0, 0.619165,0.00132254)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.805194,-0.00732643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839587,0.0320186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49296,7.92414e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332409,0.0358818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216789,-0.00988636) , 
3, -0.869864, 0, 0, 0.291909,0.0147361) , 
1, -0.637145, 0, 0, 0.45922,0.00252977) , 
0, -0.847262, 0, 0, 0.515853,0.00464103) , 
1, -0.0475709, 0, 0, 0.62094,0.00154604)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658895,-0.00147779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688474,0.0836895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76809,0.042935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617141,0.0161497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319385,-0.00515934) , 
0, -0.913081, 0, 0, 0.413154,0.0015466) , 
1, 0.298832, 0, 0, 0.461526,0.00568267) , 
3, -0.883858, 0, 0, 0.468505,0.00748818) , 
2, -0.910598, 0, 0, 0.619668,0.000792888)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676587,0.00678262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649995,-0.00433729) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783825,0.00840063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44556,-0.0151506) , 
1, 0.283425, 0, 0, 0.495248,-0.0108344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211685,-0.0728156) , 
1, -0.504829, 0, 0, 0.488221,-0.0120208) , 
2, -0.891157, 0, 0, 0.566712,-0.00768242) , 
2, -0.809524, 0, 0, 0.617603,-0.00230737)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662959,-0.0207951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611875,0.0122802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632283,-0.0804438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645475,0.0126964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458176,-0.00935587) , 
3, -0.920978, 0, 0, 0.533946,-0.00107558) , 
3, -0.792527, 0, 0, 0.537412,-0.00296283) , 
4, 0.334269, 0, 0, 0.562053,0.00115475) , 
2, -0.826319, 0, 0, 0.61304,-0.00553147)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713359,0.0791334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692997,-0.0376075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646863,0.00812037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595851,-0.00335644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267097,0.0634925) , 
1, -0.906239, 0, 0, 0.589989,-0.00166163) , 
4, -0.142912, 1, 0, 0.613735,0.00132638) , 
3, -0.587582, 0, 0, 0.615927,0.000699885) , 
3, -0.333327, 0, 0, 0.616441,0.000974596)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629632,-0.0908535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714296,0.0122696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588635,-0.00278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179694,-0.0289318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168679,-0.0841191) , 
2, -0.740877, 0, 0, 0.17653,-0.0281235) , 
1, -0.714111, 0, 0, 0.572502,-0.00310036) , 
3, -0.841392, 0, 0, 0.613674,-0.000161256) , 
3, -0.333333, 0, 0, 0.61376,-0.000467792)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656517,0.0237036) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716094,-0.0127101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59962,0.00570062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431506,-0.027484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22146,0.0152444) , 
0, -0.980175, 0, 0, 0.365604,-0.0142608) , 
3, -0.983897, 0, 0, 0.579519,0.00265046) , 
3, -0.830928, 0, 0, 0.610257,0.000409563) , 
2, -0.618155, 0, 0, 0.616729,0.00219337)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708583,-0.02247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795322,-0.00692061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522022,0.00358755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36766,0.0300936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231307,-0.00300978) , 
2, -0.957989, 0, 0, 0.325421,0.0180664) , 
2, -0.919773, 0, 0, 0.488914,0.0054016) , 
1, -0.0475052, 0, 0, 0.605123,0.00191482) , 
3, -0.733606, 0, 0, 0.616786,0.000295496)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662885,0.0040933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756384,0.0159954) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474502,-0.0292199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336336,-0.00304478) , 
2, -0.939856, 0, 0, 0.407508,-0.015298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29699,0.0509527) , 
1, -0.444822, 0, 0, 0.401193,-0.012093) , 
1, 0.213957, 0, 0, 0.470864,-0.00745209) , 
2, -0.903596, 0, 0, 0.617831,0.000240613)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910018,-0.0555802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864898,0.0227777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558255,-0.0632206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524743,-0.00374508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470695,0.0272187) , 
2, -0.495863, 1, 0, 0.521852,-0.00185397) , 
1, 0.222831, 0, 0, 0.522385,-0.00272496) , 
0, -0.764194, 0, 0, 0.57532,-0.000690675) , 
0, -0.619048, 0, 0, 0.614933,-0.00234207)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659509,0.0071535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905047,0.0776065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595061,-0.00364617) , 
1, 0.570197, 0, 0, 0.59904,-0.00215701) , 
4, -0.144887, 1, 0, 0.624275,0.000739156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266919,0.00287776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182118,-0.122385) , 
2, -0.635968, 1, 0, 0.225399,-0.0330746) , 
1, -0.906025, 0, 0, 0.617882,0.000197185)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707656,0.0553314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673677,-0.0617699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697779,0.0464306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696249,0.0291174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611356,0.000702022) , 
4, 0.737962, 0, 0, 0.614255,0.00114345) , 
4, -0.806682, 1, 0, 0.615412,0.0015902) , 
3, -0.594134, 0, 0, 0.616675,0.000809608) , 
3, -0.467211, 0, 0, 0.617868,0.00125524)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675626,0.00688905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695552,0.0404022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612163,-0.044365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647732,-0.102364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553486,-0.00552637) , 
4, -0.844566, 1, 0, 0.554981,-0.0054683) , 
4, 0.632126, 0, 0, 0.56038,-0.00803332) , 
4, 0.804099, 0, 0, 0.564145,-0.00699341) , 
2, -0.815241, 0, 0, 0.6174,-0.00173279)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639715,-0.0601889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636334,0.00831698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700822,0.0425771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631018,-0.00981692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277512,0.0162191) , 
1, -0.624449, 0, 0, 0.593255,-0.00499344) , 
3, -0.619048, 0, 0, 0.59809,-0.00363246) , 
4, 0.12016, 0, 0, 0.614394,0.000329135) , 
4, 0.809524, 0, 0, 0.614769,-0.000299518)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68793,-0.000961011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579402,-0.0322475) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644465,0.0852238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533018,0.0125206) , 
2, -0.550035, 0, 0, 0.537305,0.0114266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513104,-0.0803104) , 
2, -0.324905, 1, 0, 0.536999,0.0107095) , 
4, -0.711902, 1, 0, 0.539337,0.00869314) , 
3, -0.911194, 0, 0, 0.619321,0.003697)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753136,0.00652066) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654492,0.0672443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531701,-0.000372537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387716,-0.0138193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229096,-0.0452487) , 
2, -0.902957, 0, 0, 0.370189,-0.0141069) , 
1, -0.358789, 0, 0, 0.415622,-0.0102248) , 
3, -0.52381, 0, 0, 0.424476,-0.00794618) , 
1, -0.251879, 0, 0, 0.616651,-0.000967409)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659108,-0.106695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669539,0.00329495) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353248,0.000800723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225928,-0.0420177) , 
3, -0.869178, 0, 0, 0.302877,-0.0113738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272705,0.0674684) , 
3, -0.972802, 0, 0, 0.301359,-0.0086169) , 
1, -0.531397, 0, 0, 0.615681,0.000663233) , 
3, -0.428571, 0, 0, 0.616097,3.38168e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65156,-0.0217361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.856771,-0.00539147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533674,0.00167225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473157,0.0655127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438837,0.0161658) , 
4, -0.71148, 1, 0, 0.440618,0.0171942) , 
2, -0.876835, 0, 0, 0.492726,0.00831645) , 
0, -0.832176, 0, 0, 0.616323,0.00467939) , 
2, -0.630482, 0, 0, 0.621641,0.00222968)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696332,-0.00258292) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369184,0.0135919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35734,-0.014448) , 
4, 0.320898, 1, 0, 0.367207,0.0070045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288858,0.136108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285032,0.0300835) , 
1, -0.971409, 0, 0, 0.286947,0.0467843) , 
1, -0.945496, 0, 0, 0.363894,0.00864621) , 
1, -0.428506, 0, 0, 0.620057,0.000666752)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677982,-0.0254731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614969,-0.00111293) , 
4, -0.714943, 1, 0, 0.617522,-0.00142861) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663808,0.0430697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552566,-0.0714566) , 
3, -0.86753, 0, 0, 0.605356,-0.00796348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538134,-0.11172) , 
3, -0.68915, 1, 0, 0.581395,-0.0289103) , 
2, -0.260964, 1, 0, 0.616924,-0.00188366)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622747,-0.00631766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706517,0.0464344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622228,0.00431315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505677,0.0400173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394242,-0.0641635) , 
4, -0.036043, 0, 0, 0.489665,0.0199244) , 
4, 0.0331742, 0, 0, 0.610871,0.00442953) , 
4, 0.800357, 0, 0, 0.613612,0.00521313) , 
4, -0.0476802, 1, 0, 0.617903,0.000720975)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651328,-0.0652487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702561,0.0564394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631808,0.000459952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23926,-0.0103305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228048,-0.0751326) , 
1, -0.948675, 0, 0, 0.236509,-0.0170825) , 
1, -0.820349, 0, 0, 0.616895,-0.000338456) , 
4, -0.825113, 1, 0, 0.617754,9.31648e-05) , 
4, 0.809653, 0, 0, 0.618219,-0.000517935)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709435,0.0313958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703266,-0.0389004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656237,0.00402439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584688,-0.00325651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488325,-0.0529709) , 
4, -0.180964, 0, 0, 0.579309,-0.00437609) , 
4, -0.239848, 1, 0, 0.606726,-0.0018437) , 
3, -0.704174, 0, 0, 0.611468,-0.00280418) , 
3, -0.611713, 0, 0, 0.61553,-0.0019208)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623778,-0.0822921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726305,0.0137894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621304,0.037737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652426,0.000325148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27615,-0.0122625) , 
1, -0.530325, 0, 0, 0.604283,-0.000953335) , 
2, -0.391381, 0, 0, 0.604687,-0.000453369) , 
3, -0.733673, 0, 0, 0.617645,0.000411846) , 
3, -0.378414, 0, 0, 0.617683,9.48853e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623217,-0.00414513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665497,-0.00268599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795854,-0.0113218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632362,0.0461999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33013,0.0158885) , 
0, -0.945367, 0, 0, 0.451753,0.0235255) , 
0, -0.856397, 0, 0, 0.514602,0.0180681) , 
4, -0.250026, 1, 0, 0.61543,0.00481933) , 
4, 0.0488882, 0, 0, 0.619125,0.00118617)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692344,0.00904162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60882,-0.0160259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551568,-0.00388695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47279,0.0211802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228669,-0.0117986) , 
1, -0.288994, 0, 0, 0.41895,0.0132227) , 
3, -0.961944, 0, 0, 0.493842,0.0039189) , 
2, -0.849326, 0, 0, 0.537767,-0.00155779) , 
3, -0.911202, 0, 0, 0.620695,0.00222714)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.850906,0.016921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763938,-0.0541483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766965,0.0212565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841519,0.0147247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455761,-0.0069357) , 
0, -0.84365, 0, 0, 0.515054,-0.00372414) , 
1, -0.0292277, 0, 0, 0.547993,-0.00147688) , 
1, 0.0729942, 0, 0, 0.560237,-0.0031164) , 
1, 0.126652, 0, 0, 0.619305,-0.000877501)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721093,-0.00507587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418307,0.0382417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510286,-0.00688974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286612,0.0323362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286153,-0.00901085) , 
1, -0.501193, 1, 0, 0.286455,0.0125126) , 
0, -0.969661, 0, 0, 0.393396,0.00379191) , 
4, 0.396542, 0, 0, 0.396402,0.00707268) , 
1, -0.345333, 0, 0, 0.620427,-4.46805e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691419,-0.0394245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6288,0.00232611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269233,0.0572328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232298,-0.0243836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166473,-0.0949568) , 
2, -0.612015, 1, 0, 0.206715,-0.0310277) , 
1, -0.963762, 1, 0, 0.216197,-0.0213335) , 
1, -0.809524, 0, 0, 0.614943,0.000857347) , 
3, -0.619048, 0, 0, 0.618404,-0.000188143)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715845,0.040062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703178,0.0149913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668618,-0.0266069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628076,0.0110761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59206,-0.00363041) , 
4, 0.190869, 0, 0, 0.601795,0.000176286) , 
4, 0.50351, 0, 0, 0.605385,-0.000754706) , 
4, 0.569169, 0, 0, 0.617324,0.000524779) , 
4, -0.809524, 1, 0, 0.618582,0.000877458)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657893,-0.0103901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668616,0.0604298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654223,-0.000118488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615396,0.0485592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503091,0.00458426) , 
3, -0.924878, 0, 0, 0.513098,0.00663051) , 
3, -0.916964, 0, 0, 0.593272,0.00282033) , 
3, -0.416943, 0, 0, 0.594089,0.00323019) , 
4, 0.238095, 0, 0, 0.616831,-0.000365928)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667473,-0.0275233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718997,0.0128551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644114,0.000871313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515211,-0.0284346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391292,0.00218393) , 
3, -0.948635, 0, 0, 0.441173,-0.00867785) , 
2, -0.914957, 0, 0, 0.603782,-0.00126467) , 
3, -0.714286, 0, 0, 0.615423,-0.000405414) , 
4, -0.714304, 1, 0, 0.61751,-0.00114309)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadBDTG::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 130008.929688;
   fMax_1[0][0] = 4502359.5;
   fMin_1[1][0] = 130000.882812;
   fMax_1[1][0] = 2961852.25;
   fMin_1[2][0] = 130000.882812;
   fMax_1[2][0] = 4502359.5;
   fMin_1[0][1] = 0.00274670124054;
   fMax_1[0][1] = 8.58735179901;
   fMin_1[1][1] = 0.000602945685387;
   fMax_1[1][1] = 8.43200778961;
   fMin_1[2][1] = 0.000602945685387;
   fMax_1[2][1] = 8.58735179901;
   fMin_1[0][2] = 26188.8964844;
   fMax_1[0][2] = 658510.9375;
   fMin_1[1][2] = 25732.546875;
   fMax_1[1][2] = 678091.8125;
   fMin_1[2][2] = 25732.546875;
   fMax_1[2][2] = 678091.8125;
   fMin_1[0][3] = 25000.5683594;
   fMax_1[0][3] = 408512.8125;
   fMin_1[1][3] = 25000.3222656;
   fMax_1[1][3] = 436327.03125;
   fMin_1[2][3] = 25000.3222656;
   fMax_1[2][3] = 436327.03125;
   fMin_1[0][4] = -4.51573801041;
   fMax_1[0][4] = 4.51303291321;
   fMin_1[1][4] = -4.52842617035;
   fMax_1[1][4] = 4.51245260239;
   fMin_1[2][4] = -4.52842617035;
   fMax_1[2][4] = 4.51303291321;
}

//_______________________________________________________________________
inline void ReadBDTG::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadBDTG::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadBDTG::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
