#ifndef H4LBDTWEIGHTS_H4LBDTWEIGHTSDICT_H
#define H4LBDTWEIGHTS_H4LBDTWEIGHTSDICT_H

#if defined(__GCCXML__) and not defined(EIGEN_DONT_VECTORIZE)
#define EIGEN_DONT_VECTORIZE
#endif // __GCCXML__

#include "H4lBDTWeights/H4lBDTWeights.h"

#endif // H4LBDTWEIGHTS_H4LBDTWEIGHTSDICT_H
