import sys,os
import makeWeightMetaData
import re

def makeMetaHFiles(inputDir, prefix):
    os.system('cd '+inputDir)
    all_var_file = "all_channel_variations.h"
    output = open(all_var_file,'w')
    output.write("// Make a map of all variation maps called m_variations\n")
    output.write("// Generated by python script makeMetaHFiles.py\n")
    output.write("\n")
    #output.write("std::map<int, std::map<std::string, int>> m_variations;\n")
    #output.write("\n")
    #go into to every subdirectory
    for d in os.listdir(inputDir):
        if "mc15_13TeV." not in d: 
            continue
        #get the channel number of the subdirectory
        m = re.search("(\d+?)(?=\.)",d)
        mcChan = str(m.group(0))
        print "Making .h file for DSID "+mcChan
        #take the first file and run checkMetaSG.py on it
        firstFile = ""
        for fi in os.listdir(inputDir+"/"+d):
            if ".root" not in fi: 
                continue
            firstFile = fi
            break
        if ".root" not in firstFile: 
            print "no root file in "+d+". Skipping."
            continue
        print "Will use file "+firstFile
        print "checkMetaSG.py "+inputDir+"/"+d+"/"+firstFile+" | tee metadata_"+mcChan+".txt"
        os.system("checkMetaSG.py "+inputDir+"/"+d+"/"+firstFile+" | tee metadata_"+mcChan+".txt")
        #run makeWeightMetaData and put all created .h files in inputDir
        inFile = "metadata_"+mcChan+".txt"
        outFile = prefix+"_"+mcChan+".h"
        makeWeightMetaData.makeWeightMetaData(inFile,mcChan,outFile) 
        #include the h file in all_variations.h
        output.write('#include "Variations/'+prefix+'_'+str(mcChan)+'.h"\n')
    output.close
    print "done."

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print "This program makes a .h file of the weight variations for each DSID in 'inputDir'"
        print "Command needs to be in form 'python makeMetaHFiles.py inputDir prefix'"
        print "athena needs to be setup for checkMetaSG.py to work. i.e. asetup 20.7.5.2,here"
        exit(1)
    inputDir = sys.argv[1]
    prefix = sys.argv[2]
    makeMetaHFiles(inputDir,prefix)
